In [71]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.tokenize import TreebankWordTokenizer
import nltk.data
import re

In [106]:
parag = "hell5 my name ashish am currently involve in CE. ashish gywalqwi 1996. i "
tokenizer = nltk.data.load('/Users/ashishgyawali/nltk_data/tokenizers/punkt/english.pickle')
#cd
 
#matrch    
print(re.match(r".*",parag))
print(re.match(r"[a-zA-Z ]+",parag))
re.match(r"[a-zA-Z\d .]+",parag)


<_sre.SRE_Match object; span=(0, 73), match='hell5 my name ashish am currently involve in CE. >
<_sre.SRE_Match object; span=(0, 4), match='hell'>


<_sre.SRE_Match object; span=(0, 73), match='hell5 my name ashish am currently involve in CE. >

In [99]:
sentence = "hello my name is ashish in 1998"
re.match(r"[a-zA-Z\d]*",sentence)
re.match(r"[\d ]*",sentence)

sentenc = "I love avengers avengers"
print(re.sub(r"avengers","justice league",sentenc))

print(re.sub(r"[a-z]","0",sentenc,flags=re.I))
print(re.sub(r"[a-z]","0",sentenc,2,flags=re.I))




I love justice league justice league
0 0 0 0
0 0ove avengers avengers


In [126]:
sen1 = "welcome to my tutorials 456"
sen2 = "What %!@#$%^&* a re WEE gonna study at @you palace"
sen3 = "i        love         you"

sen1_modified = re.sub(r"\d","",sen1)
print(sen1_modified)

sen2_modified = re.sub(r"[@#$%\.]","",sen2)
print(sen2_modified)

sen2_modified = re.sub(r"\W"," ",sen2)
sen2_modified = re.sub(r"\s+"," ",sen2_modified)
sen2_modified = re.sub(r"\s+[a-zA-z]\s+"," ",sen2_modified)
print(sen2_modified)

welcome to my tutorials 
What !^&* a re WEE gonna study at you palace
What re WEE gonna study at you palace


In [156]:
x =["This ia a wolf #scary",
   "Welcome to my tutorials",
   "123 the numbe is ??",
   "Rememebr the name s - Ashish"]

for i in range(len(x)):
     x[i] = re.sub(r"\W"," ",x[i])
     x[i] = re.sub(r"\d"," ",x[i])
     x[i] = re.sub(r"\s+[a-zA-z]\s+"," ",x[i])
     x[i] = re.sub("\s+"," ",x[i])
     x[i] = re.sub("^\s","",x[i])
     x[i] = re.sub("\s$","",x[i])
print(x)

['This ia wolf scary', 'Welcome to my tutorials', 'the numbe is', 'Rememebr the name Ashish']


In [155]:
paragg = "A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs."
myarray = ['car','bus']
#myarray = sent_tokenize(parag)
for i in range(len(x)):
    myarray = word_tokenize(x[i])
array = word_tokenize(paragg)
print(myarray)
#array[2]

#myarray
#myarray[1]
#tokenizer


['Rememebr', 'the', 'name', 'Ashish']


In [64]:
word_tokenize(parag)

['hell0',
 'my',
 'name',
 'ashish',
 'ashish',
 'gywali',
 '.',
 'i',
 'am',
 'currently',
 'involve',
 'in',
 'CE',
 '.']

In [177]:
import numpy as np

In [190]:
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,9,2))
print(np.arange(1,9,dtype='float64'))


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[1.  2.1 3.2 4.3 5.4 6.5 7.6 8.7]


In [199]:
aa = np.arange(1,10)
aa.ndim
print(aa.shape)
print(aa.size)
print(aa.dtype)
print(aa.itemsize)
aa.itemsize*aa.size

(9,)
9
int64
8


72

In [200]:
%timeit list1 = range(1,1000)

266 ns ± 7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [202]:
%timeit list1 = np.arange(1,1000)

1.15 µs ± 28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [251]:
a = np.asarray([1,2,3,6,4,5])
a[1]

2

In [205]:
list2d = [[1,2,3],[1,3,4]]
np.asarray(list2d)

array([[1, 2, 3],
       [1, 3, 4]])

In [208]:
np.zeros((3,4),dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [216]:
print(np.linspace(1,4,num=8))
np.linspace(1,4,num=8,endpoint=False)

[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]


array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625])

In [221]:
np.random.random((3,4))
#matrix generates

array([[0.29388411, 0.37581734, 0.98606725, 0.79715009],
       [0.63169975, 0.93781981, 0.56434419, 0.78573595],
       [0.25067426, 0.41083509, 0.73657961, 0.2217798 ]])

In [226]:
rarr = np.random.random((3,4))
print(rarr)
np.max(rarr,axis=0)
np.max(rarr)

[[0.86709843 0.1911214  0.08715518 0.42001252]
 [0.37490911 0.71475952 0.67277985 0.93684888]
 [0.57509563 0.99789038 0.51357916 0.9358127 ]]


0.997890378242454

In [227]:
np.median(rarr,axis=0)

array([0.57509563, 0.71475952, 0.51357916, 0.9358127 ])

In [228]:
np.min(rarr)

0.08715518021685187

In [230]:
new_rarr = np.reshape(rarr,(12,))
print(new_rarr)

[0.86709843 0.1911214  0.08715518 0.42001252 0.37490911 0.71475952
 0.67277985 0.93684888 0.57509563 0.99789038 0.51357916 0.9358127 ]


In [234]:
new_rarr = np.reshape(rarr,(6,2))
print(new_rarr)

[[0.86709843 0.1911214 ]
 [0.08715518 0.42001252]
 [0.37490911 0.71475952]
 [0.67277985 0.93684888]
 [0.57509563 0.99789038]
 [0.51357916 0.9358127 ]]


In [241]:
#slicing
rarr= np.random.random((4,5))
print(rarr[:,:])
rarr[1:3,3:5]
rarr[:,1:]
rarr[:-1,:]
rarr[:-3,:]

[[0.18063431 0.63367424 0.39960151 0.19267851 0.1409109 ]
 [0.49813999 0.36386036 0.55372478 0.0485179  0.68213872]
 [0.55428568 0.07597071 0.24948326 0.57466627 0.212484  ]
 [0.75406589 0.80605757 0.3973453  0.54868671 0.69120892]]


array([[0.18063431, 0.63367424, 0.39960151, 0.19267851, 0.1409109 ]])

In [247]:
import pandas as pd

In [261]:
x = pd.Series([1,2,3,4,5])
print(x[2])

3


In [269]:
x1 = x + 100
x1 = (x ** 2) + 100
x1 = x > 2 #check
larger_than_2 = x > 2
larger_than_2.any()
larger_than_2.all()
#print(x1)

False

In [291]:
def f(x):
    if x % 2 == 0:
            return(2 * x)
    else:
        return(3 * x)
x.apply(f)

0     3
1     4
2     9
3     8
4    15
dtype: int64

In [305]:
x.astype(np.float64)
x
y = x  
y[0] = 100
x
x = pd.Series([1,2,3,4,5])
y = x.copy()
y[0] = 100
x
y


0    100
1      2
2      3
3      4
4      5
dtype: int64

In [338]:
#dataframe
data = [1,2,3,4,5,6,7,8]
df = pd.DataFrame(data,columns=["x"])
df
df["x+2"] = df["x"] + 2
df["x_sq"] = df["x"] ** 2
df = df.drop("x_sq",1)

df
df.describe()

x       x+2
count  8.00000   8.00000
mean   4.50000   6.50000
std    2.44949   2.44949
min    1.00000   3.00000
25%    2.75000   4.75000
50%    4.50000   6.50000
75%    6.25000   8.25000
max    8.00000  10.00000

In [322]:
dataseries = df["x+2"]
dataseries

0     3
1     4
2     5
3     6
4     7
5     8
6     9
7    10
Name: x+2, dtype: int64

In [349]:
datasets = pd.read_csv('match.csv')
datasets.head()

Match_Id Match_Date  Team_Name_Id  Opponent_Team_Id  Season_Id  \
0    335987  18-Apr-08             2                 1          1   
1    335988  19-Apr-08             4                 3          1   
2    335989  19-Apr-08             6                 5          1   
3    335990  20-Apr-08             7                 2          1   
4    335991  20-Apr-08             1                 8          1   

                                   Venue_Name  Toss_Winner_Id Toss_Decision  \
0                       M Chinnaswamy Stadium               2         field   
1  Punjab Cricket Association Stadium, Mohali               3           bat   
2                            Feroz Shah Kotla               5           bat   
3                            Wankhede Stadium               7           bat   
4                                Eden Gardens               8           bat   

   IS_Superover  IS_Result  Is_DuckWorthLewis    Win_Type  Won_By  \
0             0          1                  0     by runs   140.0   
1             0          1                  0     by runs    33.0   
2             0          1                  0  by wickets     9.0   
3             0          1                  0  by wickets     5.0   
4             0          1                  0  by wickets     5.0   

   Match_Winner_Id  Man_Of_The_Match_Id  First_Umpire_Id  Second_Umpire_Id  \
0              1.0                  2.0              470               477   
1              3.0                 19.0              471               487   
2              6.0                 90.0              472               512   
3              2.0                 11.0              473               476   
4              1.0                  4.0              474               486   

    City_Name Host_Country  
0   Bangalore        India  
1  Chandigarh        India  
2       Delhi        India  
3      Mumbai        India  
4     Kolkata        India